name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run tests
        run: mvn test