@startuml
actor Разработчик as Dev
actor Администратор as Admin
actor "CI/CD Система" as CI

usecase "Создание репозитория" as UC1
usecase "Клонирование репозитория" as UC2
usecase "Commit изменений" as UC3
usecase "Push изменений" as UC4
usecase "Создание ветки" as UC5
usecase "Merge веток" as UC6
usecase "Разрешение  конфликтов" as UC7
usecase "Управление разрешениями" as UC8
usecase "Trigger Build" as UC9

Dev --> UC1
Dev --> UC2
Dev --> UC3
Dev --> UC4
Dev --> UC5
Dev --> UC6
Dev --> UC7
Admin --> UC1
Admin --> UC8
CI --> UC4
CI --> UC9
@enduml
